<script lang="ts">
	import { onMount } from 'svelte';
	import { env } from '$env/dynamic/public';
	import { getConsent, setConsent, clearConsent, onConsentChange } from '$lib/consent';
	import { t } from '$lib/i18n';
	import type { Messages } from '$lib/i18n';

	interface Marker {
		lat: number;
		lng: number;
		title: string;
		description: string;
		type: 'cottage' | 'ww2' | 'nature' | 'towns' | 'heritage' | 'museums';
	}

	interface Props {
		markers: Marker[];
		center?: [number, number];
		zoom?: number;
		height?: string;
		fitBounds?: boolean;
		routeLine?: boolean;
		messages?: Messages;
		// Optional path to a self-hosted Static Maps PNG. When provided,
		// renders as the SSR'd map preview behind the consent overlay so
		// crawlers and pre-consent visitors see a real map. Generated by
		// scripts/fetch-static-map.mjs; degrades gracefully if missing.
		staticMapSrc?: string;
		staticMapSrcset?: string;
		staticMapAlt?: string;
	}

	let {
		markers,
		center = [49.172937, -0.988765],
		zoom = 10,
		height = '500px',
		fitBounds = false,
		routeLine = false,
		messages,
		staticMapSrc,
		staticMapSrcset,
		staticMapAlt = ''
	}: Props = $props();

	let mapContainer: HTMLDivElement;
	let missingKey = $state(false);
	let consented = $state(false);
	let mapLoaded = $state(false);

	const TYPE_GLYPHS: Record<string, string> = {
		cottage: '🏠',
		ww2: '⚔️',
		nature: '🌿',
		towns: '🏘️',
		heritage: '🏛️',
		museums: '🏛️'
	};

	function tx(key: string, fallback: string): string {
		if (!messages) return fallback;
		const v = t(messages, key);
		return v === key ? fallback : v;
	}

	function computeFitZoom(ms: Marker[], container: HTMLDivElement): number {
		if (ms.length < 2 || !container) return 10;
		const lats = ms.map((m) => m.lat);
		const lngs = ms.map((m) => m.lng);
		const latSpan = Math.max(...lats) - Math.min(...lats);
		const lngSpan = Math.max(...lngs) - Math.min(...lngs);
		const w = Math.max(container.offsetWidth, 200) - 80;
		const h = Math.max(container.offsetHeight, 200) - 80;
		const TILE = 256;
		const lngFraction = lngSpan / 360;
		const cosLat = Math.cos((Math.max(...lats) * Math.PI) / 180);
		const latFraction = latSpan / 360 / Math.max(cosLat, 0.1);
		const lngZoom = Math.log2(w / TILE / lngFraction);
		const latZoom = Math.log2(h / TILE / latFraction);
		const zoom = Math.floor(Math.min(lngZoom, latZoom));
		return Math.max(2, Math.min(14, zoom));
	}

	async function loadMap() {
		if (mapLoaded) return;
		const apiKey = env.PUBLIC_GOOGLE_MAPS_API_KEY;
		if (!apiKey) {
			missingKey = true;
			return;
		}
		mapLoaded = true;

		const { Loader } = await import('@googlemaps/js-api-loader');
		const loader = new Loader({ apiKey, version: 'weekly' });
		const { Map, InfoWindow, LatLngBounds, Polyline } = await loader.importLibrary('maps');
		const { Marker } = await loader.importLibrary('marker');

		let initialCenter = { lat: center[0], lng: center[1] };
		let initialZoom = zoom;
		if (fitBounds && markers.length > 1) {
			const lats = markers.map((m) => m.lat);
			const lngs = markers.map((m) => m.lng);
			initialCenter = {
				lat: (Math.min(...lats) + Math.max(...lats)) / 2,
				lng: (Math.min(...lngs) + Math.max(...lngs)) / 2
			};
			initialZoom = computeFitZoom(markers, mapContainer);
		}

		const map = new Map(mapContainer, {
			center: initialCenter,
			zoom: initialZoom,
			maxZoom: fitBounds ? 14 : undefined,
			mapTypeControl: false,
			streetViewControl: false,
			fullscreenControl: false
		});
		const infoWindow = new InfoWindow();

		for (const m of markers) {
			const glyph = TYPE_GLYPHS[m.type] || '📍';
			const marker = new Marker({
				position: { lat: m.lat, lng: m.lng },
				map,
				title: m.title,
				label: { text: glyph, fontSize: '20px' },
				icon: {
					path: 'M 0,0 m -16,-16 a 16,16 0 1,0 32,0 a 16,16 0 1,0 -32,0',
					fillColor: 'transparent',
					strokeColor: 'transparent',
					scale: 1
				}
			});
			marker.addListener('click', () => {
				infoWindow.setContent(
					`<div style="font-size:0.85rem;"><strong>${m.title}</strong><br>${m.description}</div>`
				);
				infoWindow.open({ map, anchor: marker });
			});
		}

		if (routeLine && markers.length >= 2) {
			try {
				new Polyline({
					path: markers.slice(0, 2).map((m) => ({ lat: m.lat, lng: m.lng })),
					geodesic: true,
					strokeColor: 'transparent',
					strokeOpacity: 0,
					icons: [
						{
							icon: {
								path: 'M 0,-1 0,1',
								strokeColor: '#7a4a2a',
								strokeOpacity: 0.85,
								strokeWeight: 2.5,
								scale: 3
							},
							offset: '0',
							repeat: '12px'
						}
					],
					map
				});
			} catch (e) {
				console.warn('GoogleMap: route polyline failed to render', e);
			}
		}

		if (fitBounds && markers.length > 1) {
			const bounds = new LatLngBounds();
			for (const m of markers) bounds.extend({ lat: m.lat, lng: m.lng });
			setTimeout(() => {
				try {
					map?.fitBounds(bounds, 40);
				} catch (e) {
					console.warn('fitBounds failed', e);
				}
			}, 120);
		}
	}

	function handleEnable() {
		setConsent('accepted');
		// onConsentChange listener flips `consented` and triggers loadMap()
	}

	function handleChangeChoice() {
		// Re-open the original consent banner so the guest can pick again.
		// This is the only path back into the dialog after declining — the
		// footer used to host this link but it lived too far from the
		// affected feature, so it was moved into the map overlay itself.
		clearConsent();
	}

	onMount(() => {
		consented = getConsent() === 'accepted';
		if (consented) loadMap();

		const unsubscribe = onConsentChange((choice) => {
			if (choice === 'accepted') {
				consented = true;
				loadMap();
			} else {
				// User revoked consent — we can't easily tear down a mounted map.
				// Mark as un-consented so future re-mounts gate correctly; existing
				// map instance remains until navigation. Acceptable trade-off.
				consented = false;
			}
		});

		return unsubscribe;
	});
</script>

<div bind:this={mapContainer} class="map" style="height: {height};">
	{#if missingKey}
		<div class="map__placeholder">
			<p>Map preview unavailable in this environment</p>
			<p class="map__placeholder-note">
				Set <code>PUBLIC_GOOGLE_MAPS_API_KEY</code> to display the map
			</p>
		</div>
	{:else if !consented}
		{#if staticMapSrc}
			<img
				class="map__static-fallback"
				src={staticMapSrc}
				srcset={staticMapSrcset}
				alt={staticMapAlt}
				loading="eager"
				decoding="async"
				width="640"
				height="360"
			/>
		{/if}
		<div class="map__consent" class:map__consent--over-image={staticMapSrc}>
			<svg
				class="map__consent-icon"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="1.5"
				stroke-linecap="round"
				stroke-linejoin="round"
				aria-hidden="true"
			>
				<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
				<circle cx="12" cy="10" r="3" />
			</svg>
			<p class="map__consent-title">
				{tx('cookies.map_blocked.title', 'Map needs Google Maps cookies')}
			</p>
			<p class="map__consent-body">
				{tx(
					'cookies.map_blocked.body',
					'This map is powered by Google Maps, which sets third-party cookies. Enable optional cookies to view it.'
				)}
			</p>
			<button type="button" class="map__consent-cta" onclick={handleEnable}>
				{tx('cookies.map_blocked.cta', 'Show map')}
			</button>
			<button type="button" class="map__consent-secondary" onclick={handleChangeChoice}>
				{tx('cookies.map_blocked.change_choice', 'Change cookie choice')}
			</button>
		</div>
	{/if}
</div>

<style>
	.map {
		width: 100%;
		border-radius: 0.5rem;
		overflow: hidden;
		background: var(--color-cream, #f5f0e8);
	}
	.map__placeholder {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100%;
		gap: 0.25rem;
		color: var(--color-text-muted, #5f5e5a);
		font-size: 0.875rem;
		text-align: center;
		padding: 1rem;
	}
	.map__placeholder-note {
		font-size: 0.75rem;
		opacity: 0.7;
	}
	.map__placeholder code {
		background: var(--color-cream-dark, #ede6d8);
		padding: 0 0.25rem;
		border-radius: 0.125rem;
	}

	.map__consent {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100%;
		gap: 0.4rem;
		padding: 0.85rem 1rem;
		text-align: center;
		color: var(--theme-text, #2b2b2b);
		background: var(--theme-surface, var(--color-cream, #f5f0e8));
	}

	/* Self-hosted Static Maps PNG sits behind the consent overlay so the
	   SSR'd HTML carries a real map preview for crawlers / no-JS / pre-
	   consent visitors. The overlay sits on top with a translucent scrim
	   so the prompt stays readable over any map colour. */
	.map__static-fallback {
		position: absolute;
		inset: 0;
		width: 100%;
		height: 100%;
		object-fit: cover;
	}
	.map {
		position: relative;
	}
	.map__consent--over-image {
		position: absolute;
		inset: 0;
		background: color-mix(in srgb, var(--theme-surface, var(--color-cream, #f5f0e8)) 88%, transparent);
		backdrop-filter: blur(2px);
	}
	.map__consent-icon {
		width: 1.75rem;
		height: 1.75rem;
		color: var(--theme-accent, #7a4a2a);
		opacity: 0.75;
		flex-shrink: 0;
	}
	.map__consent-title {
		margin: 0;
		font-family: var(--theme-font-display, inherit);
		font-weight: 600;
		font-size: 0.95rem;
		color: var(--theme-warm, var(--color-text, #2b2b2b));
	}
	.map__consent-body {
		margin: 0;
		max-width: 32rem;
		font-size: 0.82rem;
		line-height: 1.4;
		color: var(--theme-text-muted, var(--color-text-muted, #5f5e5a));
	}
	.map__consent-cta {
		margin-top: 0.25rem;
		padding: 0.45rem 1.2rem;
		font-family: inherit;
		font-size: 0.8rem;
		font-weight: 600;
		letter-spacing: 0.04em;
		color: #ffffff;
		background: var(--theme-accent, #7a4a2a);
		border: 1px solid var(--theme-accent, #7a4a2a);
		border-radius: 9999px;
		cursor: pointer;
		transition: opacity 0.2s ease;
		flex-shrink: 0;
	}
	.map__consent-cta:hover {
		opacity: 0.88;
	}
	.map__consent-cta:focus-visible {
		outline: 2px solid var(--theme-accent, #7a4a2a);
		outline-offset: 2px;
	}
	.map__consent-secondary {
		appearance: none;
		background: none;
		border: none;
		padding: 0.15rem 0.25rem;
		margin-top: 0.15rem;
		font-family: inherit;
		font-size: 0.75rem;
		color: var(--theme-text-muted, var(--color-text-muted, #5f5e5a));
		text-decoration: underline;
		text-underline-offset: 0.2em;
		cursor: pointer;
		transition: color 0.2s ease;
	}
	.map__consent-secondary:hover {
		color: var(--theme-warm, var(--color-text, #2b2b2b));
	}
	.map__consent-secondary:focus-visible {
		outline: 2px solid var(--theme-accent, #7a4a2a);
		outline-offset: 2px;
		border-radius: 2px;
	}
</style>
